{{- if and (eq .Values.cloudProvider "gcp") (.Values.gcp.configConnector.enabled) }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ include "k8s-cloud-tagger.fullname" . }}-wi-binding
  annotations:
    cnrm.cloud.google.com/project-id: {{ required "gcp.projectId is required" .Values.gcp.projectId }}
spec:
  member: serviceAccount:{{ .Values.gcp.projectId }}.svc.id.goog[{{ .Release.Namespace }}/{{ .Values.gcp.serviceAccount }}]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: {{ include "k8s-cloud-tagger.fullname" . }}
{{- end }}
