{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-cloud-tagger.fullname" . }}
  labels:
    {{- include "k8s-cloud-tagger.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if eq .Values.cloudProvider "gcp" }}
    iam.gke.io/gcp-service-account: {{ .Values.gcp.serviceAccount }}@{{ .Values.gcp.projectId }}.iam.gserviceaccount.com
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
